#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OL4RENTServices
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OL4RENT")]
	public partial class bienescercanosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBiene(Biene instance);
    partial void UpdateBiene(Biene instance);
    partial void DeleteBiene(Biene instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertTiposBiene(TiposBiene instance);
    partial void UpdateTiposBiene(TiposBiene instance);
    partial void DeleteTiposBiene(TiposBiene instance);
    partial void InsertSitio(Sitio instance);
    partial void UpdateSitio(Sitio instance);
    partial void DeleteSitio(Sitio instance);
    #endregion
		
		public bienescercanosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OL4RENTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bienescercanosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bienescercanosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bienescercanosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bienescercanosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Biene> Bienes
		{
			get
			{
				return this.GetTable<Biene>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TiposBiene> TiposBienes
		{
			get
			{
				return this.GetTable<TiposBiene>();
			}
		}
		
		public System.Data.Linq.Table<Sitio> Sitios
		{
			get
			{
				return this.GetTable<Sitio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bienes")]
	public partial class Biene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Titulo;
		
		private System.Data.Linq.Binary _Foto;
		
		private decimal _Latitud;
		
		private decimal _Longitud;
		
		private string _Direccion;
		
		private string _Normas;
		
		private short _Capacidad;
		
		private decimal _Precio;
		
		private string _Descripcion;
		
		private System.Nullable<System.DateTime> _FechaAlquiler;
		
		private short _DuracionAlquiler;
		
		private int _TipoBien_Id;
		
		private int _Usuario_Id;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<TiposBiene> _TiposBiene;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnLatitudChanging(decimal value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(decimal value);
    partial void OnLongitudChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnNormasChanging(string value);
    partial void OnNormasChanged();
    partial void OnCapacidadChanging(short value);
    partial void OnCapacidadChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaAlquilerChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAlquilerChanged();
    partial void OnDuracionAlquilerChanging(short value);
    partial void OnDuracionAlquilerChanged();
    partial void OnTipoBien_IdChanging(int value);
    partial void OnTipoBien_IdChanged();
    partial void OnUsuario_IdChanging(int value);
    partial void OnUsuario_IdChanged();
    #endregion
		
		public Biene()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._TiposBiene = default(EntityRef<TiposBiene>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Decimal(18,0) NOT NULL")]
		public decimal Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this.OnLatitudChanging(value);
					this.SendPropertyChanging();
					this._Latitud = value;
					this.SendPropertyChanged("Latitud");
					this.OnLatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Decimal(18,0) NOT NULL")]
		public decimal Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this.OnLongitudChanging(value);
					this.SendPropertyChanging();
					this._Longitud = value;
					this.SendPropertyChanged("Longitud");
					this.OnLongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(128)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Normas", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Normas
		{
			get
			{
				return this._Normas;
			}
			set
			{
				if ((this._Normas != value))
				{
					this.OnNormasChanging(value);
					this.SendPropertyChanging();
					this._Normas = value;
					this.SendPropertyChanged("Normas");
					this.OnNormasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacidad", DbType="SmallInt NOT NULL")]
		public short Capacidad
		{
			get
			{
				return this._Capacidad;
			}
			set
			{
				if ((this._Capacidad != value))
				{
					this.OnCapacidadChanging(value);
					this.SendPropertyChanging();
					this._Capacidad = value;
					this.SendPropertyChanged("Capacidad");
					this.OnCapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,0) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAlquiler", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAlquiler
		{
			get
			{
				return this._FechaAlquiler;
			}
			set
			{
				if ((this._FechaAlquiler != value))
				{
					this.OnFechaAlquilerChanging(value);
					this.SendPropertyChanging();
					this._FechaAlquiler = value;
					this.SendPropertyChanged("FechaAlquiler");
					this.OnFechaAlquilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionAlquiler", DbType="SmallInt NOT NULL")]
		public short DuracionAlquiler
		{
			get
			{
				return this._DuracionAlquiler;
			}
			set
			{
				if ((this._DuracionAlquiler != value))
				{
					this.OnDuracionAlquilerChanging(value);
					this.SendPropertyChanging();
					this._DuracionAlquiler = value;
					this.SendPropertyChanged("DuracionAlquiler");
					this.OnDuracionAlquilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoBien_Id", DbType="Int NOT NULL")]
		public int TipoBien_Id
		{
			get
			{
				return this._TipoBien_Id;
			}
			set
			{
				if ((this._TipoBien_Id != value))
				{
					if (this._TiposBiene.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoBien_IdChanging(value);
					this.SendPropertyChanging();
					this._TipoBien_Id = value;
					this.SendPropertyChanged("TipoBien_Id");
					this.OnTipoBien_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Id", DbType="Int NOT NULL")]
		public int Usuario_Id
		{
			get
			{
				return this._Usuario_Id;
			}
			set
			{
				if ((this._Usuario_Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuario_IdChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Id = value;
					this.SendPropertyChanged("Usuario_Id");
					this.OnUsuario_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Biene", Storage="_Usuario", ThisKey="Usuario_Id", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Bienes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Bienes.Add(this);
						this._Usuario_Id = value.Id;
					}
					else
					{
						this._Usuario_Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposBiene_Biene", Storage="_TiposBiene", ThisKey="TipoBien_Id", OtherKey="Id", IsForeignKey=true)]
		public TiposBiene TiposBiene
		{
			get
			{
				return this._TiposBiene.Entity;
			}
			set
			{
				TiposBiene previousValue = this._TiposBiene.Entity;
				if (((previousValue != value) 
							|| (this._TiposBiene.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiposBiene.Entity = null;
						previousValue.Bienes.Remove(this);
					}
					this._TiposBiene.Entity = value;
					if ((value != null))
					{
						value.Bienes.Add(this);
						this._TipoBien_Id = value.Id;
					}
					else
					{
						this._TipoBien_Id = default(int);
					}
					this.SendPropertyChanged("TiposBiene");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Mail;
		
		private string _NombreUsuario;
		
		private string _Contraseña;
		
		private string _UsuarioFacebook;
		
		private string _UsuarioTwitter;
		
		private EntitySet<Biene> _Bienes;
		
		private EntitySet<Sitio> _Sitios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnUsuarioFacebookChanging(string value);
    partial void OnUsuarioFacebookChanged();
    partial void OnUsuarioTwitterChanging(string value);
    partial void OnUsuarioTwitterChanged();
    #endregion
		
		public Usuario()
		{
			this._Bienes = new EntitySet<Biene>(new Action<Biene>(this.attach_Bienes), new Action<Biene>(this.detach_Bienes));
			this._Sitios = new EntitySet<Sitio>(new Action<Sitio>(this.attach_Sitios), new Action<Sitio>(this.detach_Sitios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioFacebook", DbType="NVarChar(128)")]
		public string UsuarioFacebook
		{
			get
			{
				return this._UsuarioFacebook;
			}
			set
			{
				if ((this._UsuarioFacebook != value))
				{
					this.OnUsuarioFacebookChanging(value);
					this.SendPropertyChanging();
					this._UsuarioFacebook = value;
					this.SendPropertyChanged("UsuarioFacebook");
					this.OnUsuarioFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioTwitter", DbType="NVarChar(128)")]
		public string UsuarioTwitter
		{
			get
			{
				return this._UsuarioTwitter;
			}
			set
			{
				if ((this._UsuarioTwitter != value))
				{
					this.OnUsuarioTwitterChanging(value);
					this.SendPropertyChanging();
					this._UsuarioTwitter = value;
					this.SendPropertyChanged("UsuarioTwitter");
					this.OnUsuarioTwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Biene", Storage="_Bienes", ThisKey="Id", OtherKey="Usuario_Id")]
		public EntitySet<Biene> Bienes
		{
			get
			{
				return this._Bienes;
			}
			set
			{
				this._Bienes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Sitio", Storage="_Sitios", ThisKey="Id", OtherKey="UsuarioSitio_Sitio_Id")]
		public EntitySet<Sitio> Sitios
		{
			get
			{
				return this._Sitios;
			}
			set
			{
				this._Sitios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bienes(Biene entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Bienes(Biene entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Sitios(Sitio entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Sitios(Sitio entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiposBienes")]
	public partial class TiposBiene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private int _Sitio_Id;
		
		private EntitySet<Biene> _Bienes;
		
		private EntityRef<Sitio> _Sitio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSitio_IdChanging(int value);
    partial void OnSitio_IdChanged();
    #endregion
		
		public TiposBiene()
		{
			this._Bienes = new EntitySet<Biene>(new Action<Biene>(this.attach_Bienes), new Action<Biene>(this.detach_Bienes));
			this._Sitio = default(EntityRef<Sitio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sitio_Id", DbType="Int NOT NULL")]
		public int Sitio_Id
		{
			get
			{
				return this._Sitio_Id;
			}
			set
			{
				if ((this._Sitio_Id != value))
				{
					if (this._Sitio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSitio_IdChanging(value);
					this.SendPropertyChanging();
					this._Sitio_Id = value;
					this.SendPropertyChanged("Sitio_Id");
					this.OnSitio_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposBiene_Biene", Storage="_Bienes", ThisKey="Id", OtherKey="TipoBien_Id")]
		public EntitySet<Biene> Bienes
		{
			get
			{
				return this._Bienes;
			}
			set
			{
				this._Bienes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sitio_TiposBiene", Storage="_Sitio", ThisKey="Sitio_Id", OtherKey="Id", IsForeignKey=true)]
		public Sitio Sitio
		{
			get
			{
				return this._Sitio.Entity;
			}
			set
			{
				Sitio previousValue = this._Sitio.Entity;
				if (((previousValue != value) 
							|| (this._Sitio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sitio.Entity = null;
						previousValue.TiposBienes.Remove(this);
					}
					this._Sitio.Entity = value;
					if ((value != null))
					{
						value.TiposBienes.Add(this);
						this._Sitio_Id = value.Id;
					}
					else
					{
						this._Sitio_Id = default(int);
					}
					this.SendPropertyChanged("Sitio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bienes(Biene entity)
		{
			this.SendPropertyChanging();
			entity.TiposBiene = this;
		}
		
		private void detach_Bienes(Biene entity)
		{
			this.SendPropertyChanging();
			entity.TiposBiene = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sitios")]
	public partial class Sitio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _Logo;
		
		private System.Data.Linq.Binary _CSS;
		
		private string _MailAdmin;
		
		private string _URL;
		
		private short _CantBienesPopulares;
		
		private short _CantMarcasXCont;
		
		private short _CantContBloqXUsu;
		
		private int _UsuarioSitio_Sitio_Id;
		
		private EntitySet<TiposBiene> _TiposBienes;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    partial void OnCSSChanging(System.Data.Linq.Binary value);
    partial void OnCSSChanged();
    partial void OnMailAdminChanging(string value);
    partial void OnMailAdminChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnCantBienesPopularesChanging(short value);
    partial void OnCantBienesPopularesChanged();
    partial void OnCantMarcasXContChanging(short value);
    partial void OnCantMarcasXContChanged();
    partial void OnCantContBloqXUsuChanging(short value);
    partial void OnCantContBloqXUsuChanged();
    partial void OnUsuarioSitio_Sitio_IdChanging(int value);
    partial void OnUsuarioSitio_Sitio_IdChanged();
    #endregion
		
		public Sitio()
		{
			this._TiposBienes = new EntitySet<TiposBiene>(new Action<TiposBiene>(this.attach_TiposBienes), new Action<TiposBiene>(this.detach_TiposBienes));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSS", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CSS
		{
			get
			{
				return this._CSS;
			}
			set
			{
				if ((this._CSS != value))
				{
					this.OnCSSChanging(value);
					this.SendPropertyChanging();
					this._CSS = value;
					this.SendPropertyChanged("CSS");
					this.OnCSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailAdmin", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string MailAdmin
		{
			get
			{
				return this._MailAdmin;
			}
			set
			{
				if ((this._MailAdmin != value))
				{
					this.OnMailAdminChanging(value);
					this.SendPropertyChanging();
					this._MailAdmin = value;
					this.SendPropertyChanged("MailAdmin");
					this.OnMailAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantBienesPopulares", DbType="SmallInt NOT NULL")]
		public short CantBienesPopulares
		{
			get
			{
				return this._CantBienesPopulares;
			}
			set
			{
				if ((this._CantBienesPopulares != value))
				{
					this.OnCantBienesPopularesChanging(value);
					this.SendPropertyChanging();
					this._CantBienesPopulares = value;
					this.SendPropertyChanged("CantBienesPopulares");
					this.OnCantBienesPopularesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantMarcasXCont", DbType="SmallInt NOT NULL")]
		public short CantMarcasXCont
		{
			get
			{
				return this._CantMarcasXCont;
			}
			set
			{
				if ((this._CantMarcasXCont != value))
				{
					this.OnCantMarcasXContChanging(value);
					this.SendPropertyChanging();
					this._CantMarcasXCont = value;
					this.SendPropertyChanged("CantMarcasXCont");
					this.OnCantMarcasXContChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantContBloqXUsu", DbType="SmallInt NOT NULL")]
		public short CantContBloqXUsu
		{
			get
			{
				return this._CantContBloqXUsu;
			}
			set
			{
				if ((this._CantContBloqXUsu != value))
				{
					this.OnCantContBloqXUsuChanging(value);
					this.SendPropertyChanging();
					this._CantContBloqXUsu = value;
					this.SendPropertyChanged("CantContBloqXUsu");
					this.OnCantContBloqXUsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioSitio_Sitio_Id", DbType="Int NOT NULL")]
		public int UsuarioSitio_Sitio_Id
		{
			get
			{
				return this._UsuarioSitio_Sitio_Id;
			}
			set
			{
				if ((this._UsuarioSitio_Sitio_Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioSitio_Sitio_IdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioSitio_Sitio_Id = value;
					this.SendPropertyChanged("UsuarioSitio_Sitio_Id");
					this.OnUsuarioSitio_Sitio_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sitio_TiposBiene", Storage="_TiposBienes", ThisKey="Id", OtherKey="Sitio_Id")]
		public EntitySet<TiposBiene> TiposBienes
		{
			get
			{
				return this._TiposBienes;
			}
			set
			{
				this._TiposBienes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Sitio", Storage="_Usuario", ThisKey="UsuarioSitio_Sitio_Id", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Sitios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Sitios.Add(this);
						this._UsuarioSitio_Sitio_Id = value.Id;
					}
					else
					{
						this._UsuarioSitio_Sitio_Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TiposBienes(TiposBiene entity)
		{
			this.SendPropertyChanging();
			entity.Sitio = this;
		}
		
		private void detach_TiposBienes(TiposBiene entity)
		{
			this.SendPropertyChanging();
			entity.Sitio = null;
		}
	}
}
#pragma warning restore 1591
