<?xml version="1.0" encoding="utf-8"?><Database Name="OL4RENT" Class="ChatEntornoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;Initial Catalog=OL4RENT;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OL4RENTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioFacebook" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UsuarioTwitter" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Usuario_Sesione" Member="Sesiones" ThisKey="Id" OtherKey="Usuario_Id" Type="Sesione" />
      <Association Name="Usuario_BuzonesMensaje" Member="BuzonesMensajes" ThisKey="Id" OtherKey="UsuarioBuzonMensajes_BuzonMensajes_Id" Type="BuzonesMensaje" />
      <Association Name="Usuario_Mensaje" Member="Mensajes" ThisKey="Id" OtherKey="Remitente_Id" Type="Mensaje" />
    </Type>
  </Table>
  <Table Name="dbo.Sesiones" Member="Sesiones">
    <Type Name="Sesione">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaConexion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UltimoUso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaCierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SesionID" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Sesione" Member="Usuario" ThisKey="Usuario_Id" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuzonesMensajes" Member="BuzonesMensajes">
    <Type Name="BuzonesMensaje">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UsuarioBuzonMensajes_BuzonMensajes_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BuzonesMensaje_Mensaje" Member="Mensajes" ThisKey="Id" OtherKey="MensajeBuzonMensaje_Mensaje_Id" Type="Mensaje" />
      <Association Name="Usuario_BuzonesMensaje" Member="Usuario" ThisKey="UsuarioBuzonMensajes_BuzonMensajes_Id" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mensajes" Member="Mensajes">
    <Type Name="Mensaje">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="FechaHora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Leido" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MensajeBuzonMensaje_Mensaje_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remitente_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BuzonesMensaje_Mensaje" Member="BuzonesMensaje" ThisKey="MensajeBuzonMensaje_Mensaje_Id" OtherKey="Id" Type="BuzonesMensaje" IsForeignKey="true" />
      <Association Name="Usuario_Mensaje" Member="Usuario" ThisKey="Remitente_Id" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>