#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OL4RENT.Views.Chat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OL4RENT")]
	public partial class ChatEntornoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertSesione(Sesione instance);
    partial void UpdateSesione(Sesione instance);
    partial void DeleteSesione(Sesione instance);
    partial void InsertBuzonesMensaje(BuzonesMensaje instance);
    partial void UpdateBuzonesMensaje(BuzonesMensaje instance);
    partial void DeleteBuzonesMensaje(BuzonesMensaje instance);
    partial void InsertMensaje(Mensaje instance);
    partial void UpdateMensaje(Mensaje instance);
    partial void DeleteMensaje(Mensaje instance);
    #endregion
		
		public ChatEntornoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OL4RENTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChatEntornoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatEntornoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatEntornoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatEntornoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Sesione> Sesiones
		{
			get
			{
				return this.GetTable<Sesione>();
			}
		}
		
		public System.Data.Linq.Table<BuzonesMensaje> BuzonesMensajes
		{
			get
			{
				return this.GetTable<BuzonesMensaje>();
			}
		}
		
		public System.Data.Linq.Table<Mensaje> Mensajes
		{
			get
			{
				return this.GetTable<Mensaje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Mail;
		
		private string _NombreUsuario;
		
		private string _Contraseña;
		
		private string _UsuarioFacebook;
		
		private string _UsuarioTwitter;
		
		private EntitySet<Sesione> _Sesiones;
		
		private EntitySet<BuzonesMensaje> _BuzonesMensajes;
		
		private EntitySet<Mensaje> _Mensajes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnUsuarioFacebookChanging(string value);
    partial void OnUsuarioFacebookChanged();
    partial void OnUsuarioTwitterChanging(string value);
    partial void OnUsuarioTwitterChanged();
    #endregion
		
		public Usuario()
		{
			this._Sesiones = new EntitySet<Sesione>(new Action<Sesione>(this.attach_Sesiones), new Action<Sesione>(this.detach_Sesiones));
			this._BuzonesMensajes = new EntitySet<BuzonesMensaje>(new Action<BuzonesMensaje>(this.attach_BuzonesMensajes), new Action<BuzonesMensaje>(this.detach_BuzonesMensajes));
			this._Mensajes = new EntitySet<Mensaje>(new Action<Mensaje>(this.attach_Mensajes), new Action<Mensaje>(this.detach_Mensajes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioFacebook", DbType="NVarChar(128)")]
		public string UsuarioFacebook
		{
			get
			{
				return this._UsuarioFacebook;
			}
			set
			{
				if ((this._UsuarioFacebook != value))
				{
					this.OnUsuarioFacebookChanging(value);
					this.SendPropertyChanging();
					this._UsuarioFacebook = value;
					this.SendPropertyChanged("UsuarioFacebook");
					this.OnUsuarioFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioTwitter", DbType="NVarChar(128)")]
		public string UsuarioTwitter
		{
			get
			{
				return this._UsuarioTwitter;
			}
			set
			{
				if ((this._UsuarioTwitter != value))
				{
					this.OnUsuarioTwitterChanging(value);
					this.SendPropertyChanging();
					this._UsuarioTwitter = value;
					this.SendPropertyChanged("UsuarioTwitter");
					this.OnUsuarioTwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Sesione", Storage="_Sesiones", ThisKey="Id", OtherKey="Usuario_Id")]
		public EntitySet<Sesione> Sesiones
		{
			get
			{
				return this._Sesiones;
			}
			set
			{
				this._Sesiones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_BuzonesMensaje", Storage="_BuzonesMensajes", ThisKey="Id", OtherKey="UsuarioBuzonMensajes_BuzonMensajes_Id")]
		public EntitySet<BuzonesMensaje> BuzonesMensajes
		{
			get
			{
				return this._BuzonesMensajes;
			}
			set
			{
				this._BuzonesMensajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Mensaje", Storage="_Mensajes", ThisKey="Id", OtherKey="Remitente_Id")]
		public EntitySet<Mensaje> Mensajes
		{
			get
			{
				return this._Mensajes;
			}
			set
			{
				this._Mensajes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesiones(Sesione entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Sesiones(Sesione entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_BuzonesMensajes(BuzonesMensaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_BuzonesMensajes(BuzonesMensaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Mensajes(Mensaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Mensajes(Mensaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sesiones")]
	public partial class Sesione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _FechaConexion;
		
		private System.DateTime _UltimoUso;
		
		private System.Nullable<System.DateTime> _FechaCierre;
		
		private string _SesionID;
		
		private int _Usuario_Id;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaConexionChanging(System.DateTime value);
    partial void OnFechaConexionChanged();
    partial void OnUltimoUsoChanging(System.DateTime value);
    partial void OnUltimoUsoChanged();
    partial void OnFechaCierreChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCierreChanged();
    partial void OnSesionIDChanging(string value);
    partial void OnSesionIDChanged();
    partial void OnUsuario_IdChanging(int value);
    partial void OnUsuario_IdChanged();
    #endregion
		
		public Sesione()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaConexion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaConexion
		{
			get
			{
				return this._FechaConexion;
			}
			set
			{
				if ((this._FechaConexion != value))
				{
					this.OnFechaConexionChanging(value);
					this.SendPropertyChanging();
					this._FechaConexion = value;
					this.SendPropertyChanged("FechaConexion");
					this.OnFechaConexionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoUso", DbType="DateTime NOT NULL")]
		public System.DateTime UltimoUso
		{
			get
			{
				return this._UltimoUso;
			}
			set
			{
				if ((this._UltimoUso != value))
				{
					this.OnUltimoUsoChanging(value);
					this.SendPropertyChanging();
					this._UltimoUso = value;
					this.SendPropertyChanged("UltimoUso");
					this.OnUltimoUsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCierre
		{
			get
			{
				return this._FechaCierre;
			}
			set
			{
				if ((this._FechaCierre != value))
				{
					this.OnFechaCierreChanging(value);
					this.SendPropertyChanging();
					this._FechaCierre = value;
					this.SendPropertyChanged("FechaCierre");
					this.OnFechaCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SesionID", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SesionID
		{
			get
			{
				return this._SesionID;
			}
			set
			{
				if ((this._SesionID != value))
				{
					this.OnSesionIDChanging(value);
					this.SendPropertyChanging();
					this._SesionID = value;
					this.SendPropertyChanged("SesionID");
					this.OnSesionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Id", DbType="Int NOT NULL")]
		public int Usuario_Id
		{
			get
			{
				return this._Usuario_Id;
			}
			set
			{
				if ((this._Usuario_Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuario_IdChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Id = value;
					this.SendPropertyChanged("Usuario_Id");
					this.OnUsuario_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Sesione", Storage="_Usuario", ThisKey="Usuario_Id", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Sesiones.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Sesiones.Add(this);
						this._Usuario_Id = value.Id;
					}
					else
					{
						this._Usuario_Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BuzonesMensajes")]
	public partial class BuzonesMensaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UsuarioBuzonMensajes_BuzonMensajes_Id;
		
		private EntitySet<Mensaje> _Mensajes;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsuarioBuzonMensajes_BuzonMensajes_IdChanging(int value);
    partial void OnUsuarioBuzonMensajes_BuzonMensajes_IdChanged();
    #endregion
		
		public BuzonesMensaje()
		{
			this._Mensajes = new EntitySet<Mensaje>(new Action<Mensaje>(this.attach_Mensajes), new Action<Mensaje>(this.detach_Mensajes));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioBuzonMensajes_BuzonMensajes_Id", DbType="Int NOT NULL")]
		public int UsuarioBuzonMensajes_BuzonMensajes_Id
		{
			get
			{
				return this._UsuarioBuzonMensajes_BuzonMensajes_Id;
			}
			set
			{
				if ((this._UsuarioBuzonMensajes_BuzonMensajes_Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioBuzonMensajes_BuzonMensajes_IdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioBuzonMensajes_BuzonMensajes_Id = value;
					this.SendPropertyChanged("UsuarioBuzonMensajes_BuzonMensajes_Id");
					this.OnUsuarioBuzonMensajes_BuzonMensajes_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BuzonesMensaje_Mensaje", Storage="_Mensajes", ThisKey="Id", OtherKey="MensajeBuzonMensaje_Mensaje_Id")]
		public EntitySet<Mensaje> Mensajes
		{
			get
			{
				return this._Mensajes;
			}
			set
			{
				this._Mensajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_BuzonesMensaje", Storage="_Usuario", ThisKey="UsuarioBuzonMensajes_BuzonMensajes_Id", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.BuzonesMensajes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.BuzonesMensajes.Add(this);
						this._UsuarioBuzonMensajes_BuzonMensajes_Id = value.Id;
					}
					else
					{
						this._UsuarioBuzonMensajes_BuzonMensajes_Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mensajes(Mensaje entity)
		{
			this.SendPropertyChanging();
			entity.BuzonesMensaje = this;
		}
		
		private void detach_Mensajes(Mensaje entity)
		{
			this.SendPropertyChanging();
			entity.BuzonesMensaje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mensajes")]
	public partial class Mensaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Texto;
		
		private System.DateTime _FechaHora;
		
		private bool _Leido;
		
		private int _MensajeBuzonMensaje_Mensaje_Id;
		
		private int _Remitente_Id;
		
		private EntityRef<BuzonesMensaje> _BuzonesMensaje;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTextoChanging(string value);
    partial void OnTextoChanged();
    partial void OnFechaHoraChanging(System.DateTime value);
    partial void OnFechaHoraChanged();
    partial void OnLeidoChanging(bool value);
    partial void OnLeidoChanged();
    partial void OnMensajeBuzonMensaje_Mensaje_IdChanging(int value);
    partial void OnMensajeBuzonMensaje_Mensaje_IdChanged();
    partial void OnRemitente_IdChanging(int value);
    partial void OnRemitente_IdChanged();
    #endregion
		
		public Mensaje()
		{
			this._BuzonesMensaje = default(EntityRef<BuzonesMensaje>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Texto", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Texto
		{
			get
			{
				return this._Texto;
			}
			set
			{
				if ((this._Texto != value))
				{
					this.OnTextoChanging(value);
					this.SendPropertyChanging();
					this._Texto = value;
					this.SendPropertyChanged("Texto");
					this.OnTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this.OnFechaHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaHora = value;
					this.SendPropertyChanged("FechaHora");
					this.OnFechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leido", DbType="Bit NOT NULL")]
		public bool Leido
		{
			get
			{
				return this._Leido;
			}
			set
			{
				if ((this._Leido != value))
				{
					this.OnLeidoChanging(value);
					this.SendPropertyChanging();
					this._Leido = value;
					this.SendPropertyChanged("Leido");
					this.OnLeidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MensajeBuzonMensaje_Mensaje_Id", DbType="Int NOT NULL")]
		public int MensajeBuzonMensaje_Mensaje_Id
		{
			get
			{
				return this._MensajeBuzonMensaje_Mensaje_Id;
			}
			set
			{
				if ((this._MensajeBuzonMensaje_Mensaje_Id != value))
				{
					if (this._BuzonesMensaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMensajeBuzonMensaje_Mensaje_IdChanging(value);
					this.SendPropertyChanging();
					this._MensajeBuzonMensaje_Mensaje_Id = value;
					this.SendPropertyChanged("MensajeBuzonMensaje_Mensaje_Id");
					this.OnMensajeBuzonMensaje_Mensaje_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remitente_Id", DbType="Int NOT NULL")]
		public int Remitente_Id
		{
			get
			{
				return this._Remitente_Id;
			}
			set
			{
				if ((this._Remitente_Id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRemitente_IdChanging(value);
					this.SendPropertyChanging();
					this._Remitente_Id = value;
					this.SendPropertyChanged("Remitente_Id");
					this.OnRemitente_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BuzonesMensaje_Mensaje", Storage="_BuzonesMensaje", ThisKey="MensajeBuzonMensaje_Mensaje_Id", OtherKey="Id", IsForeignKey=true)]
		public BuzonesMensaje BuzonesMensaje
		{
			get
			{
				return this._BuzonesMensaje.Entity;
			}
			set
			{
				BuzonesMensaje previousValue = this._BuzonesMensaje.Entity;
				if (((previousValue != value) 
							|| (this._BuzonesMensaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BuzonesMensaje.Entity = null;
						previousValue.Mensajes.Remove(this);
					}
					this._BuzonesMensaje.Entity = value;
					if ((value != null))
					{
						value.Mensajes.Add(this);
						this._MensajeBuzonMensaje_Mensaje_Id = value.Id;
					}
					else
					{
						this._MensajeBuzonMensaje_Mensaje_Id = default(int);
					}
					this.SendPropertyChanged("BuzonesMensaje");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Mensaje", Storage="_Usuario", ThisKey="Remitente_Id", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Mensajes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Mensajes.Add(this);
						this._Remitente_Id = value.Id;
					}
					else
					{
						this._Remitente_Id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
