//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ol4RentAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionOrigenDatos
    {
        public ConfiguracionOrigenDatos()
        {
            this.ValoresAtributo = new HashSet<ValorAtributo>();
        }
    
        public int Id { get; set; }
    
        public virtual OrigenDatos OrigenDatos { get; set; }
        public virtual ICollection<ValorAtributo> ValoresAtributo { get; set; }
        public virtual Sitio Sitio { get; set; }
    }
}
