//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ol4RentAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecificacionBien
    {
        public EspecificacionBien()
        {
            this.ValoresCaracteristicas = new HashSet<ValorCaracteristica>();
        }
    
        public int Id { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public string Direccion { get; set; }
        public short Rango { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TipoBien TipoBien { get; set; }
        public virtual ICollection<ValorCaracteristica> ValoresCaracteristicas { get; set; }
    }
}
