//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ol4RentAPI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sitio> SitioSet1 { get; set; }
        public DbSet<OrigenDatos> OrigenDatosSet { get; set; }
        public DbSet<Caracteristica> CaracteristicaSet1 { get; set; }
        public DbSet<Novedad> NovedadSet { get; set; }
        public DbSet<Bien> BienSet1 { get; set; }
        public DbSet<TipoBien> TipoBienSet { get; set; }
        public DbSet<Contenido> ContenidoSet { get; set; }
        public DbSet<Adjunto> AdjuntoSet { get; set; }
        public DbSet<Usuario> UsuarioSet { get; set; }
        public DbSet<ConfiguracionOrigenDatos> ConfiguracionOrigenDatosSet { get; set; }
        public DbSet<Rol> RolSet { get; set; }
        public DbSet<HabilitacionUsuario> HabilitacionUsuarioSet { get; set; }
        public DbSet<BuzonMensajes> BuzonMensajesSet { get; set; }
        public DbSet<Mensaje> MensajeSet { get; set; }
        public DbSet<EspecificacionBien> EspecificacionBienSet { get; set; }
        public DbSet<ValorCaracteristica> ValorCaracteristicaSet { get; set; }
        public DbSet<MeGusta> MeGustaSet { get; set; }
        public DbSet<Atributo> AtributoSet { get; set; }
        public DbSet<ValorAtributo> ValorAtributoSet { get; set; }
        public DbSet<Sesion> SesionSet { get; set; }
    }
}
