//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ol4RentAPI.Model
{
    using System;
    
    public enum TipoDato : int
    {
        ENTERO = 1,
        STRING = 2,
        DECIMAL = 3,
        BOOLEANO = 4,
        FECHA = 5
    }
}
